### PR TITLE
DATAUP-742: Add exact_match_on field to Genbank uploader

### PR DESCRIPTION
**Pull request by MrCreosote**
# Description of PR purpose/changes

Added the `exact_match_on` field to the Genbank dynamic dropdown config. This will be used in the xSV bulk import to match the user input in the xSV file to the response from the taxon API.

# Jira Ticket / Issue

e.g. <https://kbase-jira.atlassian.net/browse/DATAUP-X>

-   [X] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)

# Testing Instructions

-   Details for how to test the PR: 
-   [X] Tests pass in Travis-CI and locally 

# Dev Checklist:

-   [X] My code follows the guidelines at <https://sites.google.com/truss.works/kbasetruss/development>
-   [X] I have performed a self-review of my own code
-   [n/a] I have commented my code, particularly in hard-to-understand areas
-   [n/a] I have made corresponding changes to the documentation, including updating the README with app information changes
-   [X] My changes generate no new warnings
-   [n/a] I have added tests that prove my fix is effective or that my feature works
-   [X] New and existing tests pass locally with my changes
-   [n/a] Any dependent changes have been merged and published in downstream modules

# Updating Version and Release Notes (if applicable)

-   [X] [Version has been bumped](https://semver.org/) in `kbase.yml`
-   [X] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Comment by MrCreosote** [comment]
Lintly seems to be broken in a way that can't possibly be due to the changes here

**Comment by MrCreosote** [comment]
Codecov also seems to be a bit off, as again there's no way the current changes could've affected coverage

**Comment by MrCreosote** [comment]
https://kbase.github.io/kb_sdk_docs/references/UI_spec.html#options-for-the-dynamic-dropdown-in-spec-json

**Review by Tianhao-Gu — APPROVED** [review]
👍 LTGM

**Pull request merged**
