### PR TITLE
DATAUP-130 add PR template

### PR DESCRIPTION
**Pull request by briehl**
This adds a new pull request template to this repo, based on the work that @bio-boris did for the [narrative repo](https://github.com/kbase/narrative). It mostly follows the same pattern, with a few minor differences, and emphasis on updating the README for any apps that have changed.

### CODE REVIEW

**Review by bio-boris — APPROVED** [review]
LGTM

**Review by ialarmedalien — APPROVED** [review]
LGTM!

**Comment by leia-sefkin** [comment]
LGTM as well :)

**Comment by briehl** [comment]
That seems like consensus. Merging and moving on!

**Pull request merged**
